In [2]:
import numpy as np
import scipy.stats as sp
import matplotlib.pyplot as plt

In [21]:
def res(X,mu, sigma, Pi):
#     print(X.shape)
#     print(mu.shape)
#     print(sigma.shape)
#     print(Pi)
    d = Pi*sp.multivariate_normal.pdf(X, mu, sigma)
    return d

In [4]:
X1 = np.random.randn(500,2)*[1,2] + 5
X2 = np.random.randn(500,2)*[1,1]
X3 = np.random.randn(500,2)*[1.2,1] - [2,-6]
X = np.row_stack((X1,X2, X3))

In [72]:
M = np.row_stack((np.array([0,0]),np.array([1,1]),np.array([-1,2])))
M
sigma0 = np.eye(2)
sigma1 = np.eye(2)
sigma2 = np.eye(2)

Pi = np.ones(3)/3

In [73]:
for i in range(100):
    D0 = np.empty((len(X),1))
#     for i in range(len(X)):
    D0[:,0] = np.array(res(X[:,], M[0,], sigma0, Pi[0]), dtype = float)
    D1 = np.empty((len(X),1))
#     for i in range(len(X)):
    D1[:,0] = res(X[:,], M[1,], sigma1, Pi[1])
    D2 = np.empty((len(X),1))
#     for i in range(len(X)):
    D2[:,0] = res(X[:,], M[2,], sigma2, Pi[2])
    D = np.column_stack((D0,D1, D2))
    D = D/np.sum(D, axis = 1).reshape(-1,1)
    labels = np.argmin(D, axis = 1)
    Pi = np.mean(D,axis = 0)
    M0 = np.sum(D[:,0].reshape(-1,1)*X, axis = 0)/np.sum(D[:,0]).reshape(-1,1)
    M1 = np.sum(D[:,1].reshape(-1,1)*X, axis = 0)/np.sum(D[:,1]).reshape(-1,1)
    M2 = np.sum(D[:,2].reshape(-1,1)*X, axis = 0)/np.sum(D[:,2]).reshape(-1,1)
    M = np.row_stack((M0,M1,M2))
    sigma0 = (D[:,0].reshape(-1,1)*(X - M0)).T@(X - M0)/np.sum(D[:,0]).reshape(-1,1) + .000000001*np.eye(2)
    sigma1 = (D[:,1].reshape(-1,1)*(X - M1)).T@(X - M1)/np.sum(D[:,1]).reshape(-1,1) + .000000001*np.eye(2)
    sigma2 = (D[:,2].reshape(-1,1)*(X - M2)).T@(X - M2)/np.sum(D[:,2]).reshape(-1,1) + .000000001*np.eye(2)

In [74]:
print('These are the centers.')
print(M)
print('This is the first vcov. Should be [1,0],[0,1].')
print(sigma0)
print('This is the second vcov. Should be [1,0],[0,4].')
print(sigma1)
print('This is the third vcov. Should be [1.44,0],[0,1].')
print(sigma2)

These are the centers.
[[ 0.04740313 -0.02537135]
 [ 4.98894166  5.06782407]
 [-1.91243001  6.06968265]]
This is the first vcov. Should be [1,0],[0,1].
[[0.92701375 0.00985316]
 [0.00985316 1.08511295]]
This is the second vcov. Should be [1,0],[0,4].
[[0.97104971 0.04114447]
 [0.04114447 3.7560746 ]]
This is the third vcov. Should be [1.44,0],[0,1].
[[1.54302815 0.10964832]
 [0.10964832 0.97220476]]


In [62]:
np.sum(D, axis = 1)

array([1., 1., 1., ..., 1., 1., 1.])

In [ ]:
X1 = np.random.randn(200,2)*[1,2] + 5
X2 = np.random.randn(200,2)*[1,1]
X3 = np.random.randn(200,2)*[1.2,1] - [2,-6]