In [1]:
import numpy as np
def oneHotEncode(matrix, columns):
    for column in columns:
        uniques = np.unique(matrix[:,column])
        newmat = np.zeros((len(matrix[:,column]),len(uniques)))

        for i in range(0,len(matrix[:,column])):
            for j in range(0,len(uniques)):
                if(matrix[i,column] == uniques[j]):
                    newmat[i,j] = 1
        matrix = np.column_stack((matrix,newmat))
    try:
        matrix = np.delete(matrix,columns,axis = 1).astype(float)
    except:
        matrix = np.delete(matrix,columns,axis = 1)
    return matrix



NameError: name 'data' is not defined

In [35]:
f = [3,3,3,3,3,1]
g = [1,5,2,2,3,1]
fgmat = np.column_stack((f,g))
print(oneHotEncode(fgmat,[0]))

[[1. 0. 1.]
 [5. 0. 1.]
 [2. 0. 1.]
 [2. 0. 1.]
 [3. 0. 1.]
 [1. 1. 0.]]


In [36]:
print(oneHotEncode(fgmat,[1]))

[[3. 1. 0. 0. 0.]
 [3. 0. 0. 0. 1.]
 [3. 0. 1. 0. 0.]
 [3. 0. 1. 0. 0.]
 [3. 0. 0. 1. 0.]
 [1. 1. 0. 0. 0.]]


In [38]:
g = [1,3,3,2,2,1]
r = ["cat",'frog','dog',"cat",'dog','frog']
mat = np.column_stack((g,r))
print(oneHotEncode(mat,[0]))


[['cat' '1.0' '0.0' '0.0']
 ['frog' '0.0' '0.0' '1.0']
 ['dog' '0.0' '0.0' '1.0']
 ['cat' '0.0' '1.0' '0.0']
 ['dog' '0.0' '1.0' '0.0']
 ['frog' '1.0' '0.0' '0.0']]


In [39]:
g = [1,3,3,2,2,1]
r = ["cat",'frog','dog',"cat",'dog','frog']
mat = np.column_stack((g,r))
print(oneHotEncode(mat,[1]))


[[1. 1. 0. 0.]
 [3. 0. 0. 1.]
 [3. 0. 1. 0.]
 [2. 1. 0. 0.]
 [2. 0. 1. 0.]
 [1. 0. 0. 1.]]


In [40]:
g = [1,3,3,2,2,1]
r = ["cat",'frog','dog',"cat",'dog','frog']
mat = np.column_stack((g,r))
print(oneHotEncode(mat,[0,1]))


[[1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1.]]


In [42]:
g = [1,3,3,2,2,1]
r = ["cat",'frog','dog',"cat",'dog','frog']
k = [0,20,20,3,2,0]
mat = np.column_stack((g,r,k))
print(oneHotEncode(mat,[0,1]))


[[ 0.  1.  0.  0.  1.  0.  0.]
 [20.  0.  0.  1.  0.  0.  1.]
 [20.  0.  0.  1.  0.  1.  0.]
 [ 3.  0.  1.  0.  1.  0.  0.]
 [ 2.  0.  1.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.  0.  1.]]


In [43]:
g = [1,3,3,2,2,1]
r = ["cat",'frog','dog',"cat",'dog','frog']
k = [0,20,20,3,2,0]
mat = np.column_stack((g,r,k))
print(oneHotEncode(mat,[0,2]))


[['cat' '1.0' '0.0' '0.0' '1.0' '0.0' '0.0' '0.0']
 ['frog' '0.0' '0.0' '1.0' '0.0' '0.0' '1.0' '0.0']
 ['dog' '0.0' '0.0' '1.0' '0.0' '0.0' '1.0' '0.0']
 ['cat' '0.0' '1.0' '0.0' '0.0' '0.0' '0.0' '1.0']
 ['dog' '0.0' '1.0' '0.0' '0.0' '1.0' '0.0' '0.0']
 ['frog' '1.0' '0.0' '0.0' '1.0' '0.0' '0.0' '0.0']]


In [47]:
g = [1,3,3,2,2,1]
r = ["cat",'frog','dog',"cat",'dog','frog']
k = [0,20,20,3,2,0]
mat = np.column_stack((g,r,k))
print(oneHotEncode(mat,[0,2,1]))


[[1. 0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 1. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 1.]]
