In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
data =  pd.read_csv('Color.txt', sep = '\t').as_matrix()

/home/donald/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [6]:
data[:,3] = data[:,3] - 1

In [7]:
Y = np.matrix(data[:,3]).T
X = data[:,0:3]

In [8]:
X = np.matrix(np.column_stack((np.ones(len(X)),X)))

In [14]:
def sig(matrix):
    return 1/(1+np.exp(-matrix))
def model(data,valset,lr, epochs):
    
    Y = np.matrix(data[:,3]).T
    Yval = np.matrix(valset[:,3]).T
    Xval = valset[:,0:3]
    Xval = np.matrix(np.column_stack((np.ones(len(Xval)),Xval,np.sqrt(Xval[:,1]**2+Xval[:,2]**2+Xval[:,0]**2))))
    
    X = data[:,0:3]
    X = np.matrix(np.column_stack((np.ones(len(X)),X,np.sqrt(X[:,1]**2+X[:,2]**2+X[:,0]**2))))
    w = np.matrix(np.random.randn(X.shape[1])).T
    acclist = []
    accbest = 0
    epochbest = 0
    for i in range(0,epochs):
        w = w - lr*X.T@(np.matrix(sig(X@w))-Y)
        acc = np.mean(np.rint(sig(Xval@w)) == Yval)
        if(acc > accbest):
            accbest = acc
            epochbest = i
    return accbest, epochbest

def kfold(model, lr,data, folds = 10):
    index = int(len(data)/(folds))
    np.random.shuffle(data)
    dfolds = []
    for i in range(0,folds):
        dfolds.append(data[(i*index):((i+1)*index),])
    acclist = []
    epochlist = []
    wlist = []
    for i in range(0,folds):
        trainset = np.vstack(dfolds[:i]+dfolds[(i+1):])
        valset = dfolds[i]        
        acc, epochs = model(trainset,valset,lr, 2000)
        acclist.append(acc)
        epochlist.append(epochs)
        def sig(matrix):
            return 1/(1+np.exp(-matrix))
    return np.mean(acclist), epochlist
np.random.shuffle(data)
test = data[int(np.rint(.7*len(data))):,]
acclist = []
kfold(model,.00000001,data[0:int(np.rint(.7*len(data))),],folds = 10)


KeyboardInterrupt: 

In [ ]:
np.mean(acclist)

In [10]:
def model(data,valset,lr, epochs):
    w = np.matrix(np.random.randn(4)).T
    Y = np.matrix(data[:,3]).T
    Yval = np.matrix(valset[:,3]).T
    Xval = valset[:,0:3]
    Xval = np.matrix(np.column_stack((np.ones(len(Xval)),Xval)))
    X = data[:,0:3]
    X = np.matrix(np.column_stack((np.ones(len(X)),X)))
    for i in range(0,epochs):
        w = w - lr*X.T@(np.matrix(sig(X@w))-Y)
    return w,np.mean(np.rint(sig(Xval@w)) == Yval)
wbest,acc = model(data[0:int(np.rint(.7*len(data))),],test, .00000001, 100)

NameError: name 'test' is not defined

In [11]:
acc

NameError: name 'acc' is not defined

In [12]:
def sig(matrix):
    return 1/(1+np.exp(-matrix))
def model(data,valset,lr, epochs):
    
    Y = np.matrix(data[:,3]).T
    Yval = np.matrix(valset[:,3]).T
    Xval = valset[:,0:3]
    Xval = np.matrix(np.column_stack((np.ones(len(Xval)),Xval,np.sqrt(Xval[:,1]**2+Xval[:,2]**2+Xval[:,0]**2))))
    
    X = data[:,0:3]
    X = np.matrix(np.column_stack((np.ones(len(X)),X,np.sqrt(X[:,1]**2+X[:,2]**2+X[:,0]**2))))
    w = np.matrix(np.random.randn(X.shape[1])).T
    acclist = []
    accbest = 0
    err = []
    inds = []
    errbest = 100000000000
    for i in range(0,epochs):
        matrix = sig(X@w)
        w = w - lr*X.T@(np.matrix(matrix)-Y)
#         cost = []
#         for i in Y:
#             if i == 1:
#                 cost.append(np.log(matrix))
#             else:
#                 cost.append(np.log(1-matrix))
#         newerr = -sum(cost)
#         inds.append(i)
#         if newerr < errbest:
#             errbest = newerr
#             wbest = w
#     plt.plot(inds,err)
    print(w)
#     print(np.mean(np.rint(sig(Xval@w))))
#     print(np.mean(Yval))
    recall = np.sum(np.multiply(np.rint(sig(Xval@w)),Yval))/np.sum(Yval)
    return np.mean(np.rint(sig(Xval@w)) == Yval),w.tolist(), recall
#         if(acc > accbest):
#             accbest = acc
#     return np.mean(np.rint(sig(X@w))==Y)

In [13]:
np.random.shuffle(data)
test = data[int(np.rint(.7*len(data))):,]
acc, w, recall = model(data[0:int(np.rint(.7*len(data))),],test, .0000001, 1700)


[[-1.25258688]
 [-3.8143287 ]
 [-5.37132457]
 [-9.13081391]
 [11.16057497]]


In [10]:
X

matrix([[  1.,  74.,  85., 123.],
        [  1.,  73.,  84., 122.],
        [  1.,  72.,  83., 121.],
        ...,
        [  1., 163., 162., 112.],
        [  1., 163., 162., 112.],
        [  1., 255., 255., 255.]])

In [11]:
import MyML.TSLogisticRegression as LogReg

In [12]:
model = LogReg.TSLogisticRegression(4,1)
X = (X - np.min(X))/(np.max(X) - np.min(X))

In [ ]:
model.train(X,Y,epochs = 100, lr= .000001)

In [78]:
sum(model.prediction)

matrix([[224029.]])

In [79]:
sum(Y)

matrix([[194198]])

In [80]:
len(Y)

245057